### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by CJHFUTURE** [eridgd/AdaIN-TF#4]
Hey dude, just getting some errors when trying to train...any ideas?
(tf-keras) E:\SUGARBANK\ML\SOFTWARE\AdaIN-TF-master>python train.py --content-path E:\SUGARBANK\ML\SOFTWARE\train2014 --style-path E:\SUGARBANK\ML\ASSETS\Style --batch-size 8 --content-weight 1 --style-weight 1e-2 --tv-weight 0 --checkpoint E:\SUGARBANK\ML\AdaIN-TF-master\models\checkpoint --learning-rate 1e-4 --lr-decay 1e-5
Using TensorFlow backend.
2018-02-06 12:30:31.142079: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-02-06 12:30:32.247307: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce GTX 980M major: 5 minor: 2 memoryClockRate(GHz): 1.1265
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.71GiB
2018-02-06 12:30:32.248644: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 980M, pci bus id: 0000:01:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    train()
  File "train.py", line 128, in train
    use_gram=args.gram)
  File "E:\SUGARBANK\ML\SOFTWARE\AdaIN-TF-master\model.py", line 18, in __init__
    self.build_model(vgg_weights)
  File "E:\SUGARBANK\ML\SOFTWARE\AdaIN-TF-master\model.py", line 31, in build_model
    self.vgg_model = vgg_from_t7(vgg_weights, target_layer='relu4_1')
  File "E:\SUGARBANK\ML\SOFTWARE\AdaIN-TF-master\vgg_normalised.py", line 21, in vgg_from_t7
    t7 = torchfile.load(t7_file, force_8bytes_long=False)
  File "C:\Users\Sugar\AppData\Local\conda\conda\envs\tf-keras\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\Sugar\AppData\Local\conda\conda\envs\tf-keras\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\Sugar\AppData\Local\conda\conda\envs\tf-keras\lib\site-packages\torchfile.py", line 385, in read_obj
    k = self.read_obj()
  File "C:\Users\Sugar\AppData\Local\conda\conda\envs\tf-keras\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\Sugar\AppData\Local\conda\conda\envs\tf-keras\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\Sugar\AppData\Local\conda\conda\envs\tf-keras\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'list'

**Comment by eridgd** [comment]
This is an issue with the torchfile package on Windows. Someone provided a fix for my WCT repo that I should port over to this one -- you can access the fixed compatible version of torchfile.py here https://github.com/eridgd/WCT-TF/blob/master/torchfile.py to use instead of the pip version.

**Comment by CJHFUTURE** [comment]
Thanks heaps. Also I had to copy the vgg_normalized.py from your WCT-TF as it had some edits as well?
Cheers

**Comment by stalagmite7** [comment]
I'm trying to train using a template, I keep encountering this error:

`ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''`


I have narrowed it down to the `torchfile.py` that I downloaded from your link above in this comment thread. But beyond that, I'm not able to tell if the error is in the `read_double()` or the `read_long()` functions or how I can explicitly say to not type-check when casting, as I don't see a place where explicit casting is happening.

**Comment by eridgd** [comment]
From a quick pass of looking into this, my best guess that this is due to the version of numpy being used. Any luck when you try downgrading np?

Also, are you trying this on Windows? If not, the official version of torchfile (or at least the version from 11 months ago) should work on linux/macos.
